### ISSUE TITLE
新旧迁移相关问题

### ISSUE THREAD

**Issue by GeorgeDong32** [fuingzu/Magic-Link#1]
你好，我想问一下一些关于从ShortUrl迁移到Magic-Link相关的问题
* 数据库能否直接使用已有的mongoDBUrl

**Comment by fuingzu** [comment]
可以，注意修改一下 mongodbCollection 这个环境变量，以免新旧数据串在一起。

**Comment by GeorgeDong32** [comment]
> 可以，注意修改一下 mongodbCollection 这个环境变量，以免新旧数据串在一起。 目前暂不支持数据迁移，只能用一个新的 mongodbCollection，如果数据量不大的话可以自己在网页端上手动转移一下数据。

太好了，昨天刚自己尝试给旧版改了下UI，今天就看到有完善的新版了 😄

**Comment by fuingzu** [comment]
考古回来提醒一下）
新版本解决了很多问题，建议您重新拉一遍新版本，就是再部署一次。
保持环境变量不变，这样就不会丢失数据。
