### ISSUE TITLE
自定义字符串好像无效

### ISSUE THREAD

**Issue by 7noemo** [fuingzu/Magic-Link#2]
添加自定义短网址无法识别，还是随机码。

ps: 还有个小问题底下版权不居中  电脑网页看这有点奇怪

**Comment by 7noemo** [comment]
再补充一条：
已经新建的网址点编辑后如果不输入新的值点取消就会`null` 转换网址变空 跳转`Not found`

**Comment by fuingzu** [comment]
收到，我看看

**Comment by fuingzu** [comment]
感谢反馈。
版权问题和修改时取消变为null的问题已经解决，自定义path无法使用问题我没有成功复现，您可以拉取新的代码并按照之前的方式重新部署一遍并保证环境变量一致，这样在升级时就不会丢失数据了。
您方便的话可以发一个自定义链接无法使用的操作录屏到我的邮箱 hi#muna.uk 我看一下。

**Comment by 7noemo** [comment]
感谢优化。
自定义path无法使用可能是因为链接非首次转换的原因。
![233](https://github.com/fuingzu/Magic-Link/assets/103473489/5bf9e66c-e97e-4b36-ab42-5ceb48e7a127)

**Comment by fuingzu** [comment]
我试了一下，应该是因为长链接里面有一个 # 字符，所以导致出问题了，我再排查一下。
很感谢您的演示。

**Comment by 7noemo** [comment]
太感谢了正常了。膜拜大佬 👍 💯
